// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 9.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:86*100,delay:21*100,width:1280,height:590,autoPlay:true,autoPlayVideo:true,playPause:true,stopOnHover:false,loop:false,bullets:1,caption:true,captionEffect:"fade",controls:true,controlsThumb:["data1/tooltips/img1.jpg", "data1/tooltips/img2.jpg", "data1/tooltips/o_1.jpg"],responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:0});